version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-php
    volumes:
      - ./src:/var/www
    ports:
      - "8080:80"
    depends_on:
      - mysql



  mysql:
    image: mysql:8.0
    container_name: stock-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockdb
      MYSQL_USER: stockuser
      MYSQL_PASSWORD: stockpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # ✅ tabloyu otomatik oluşturur

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stock-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: stockuser
      PMA_PASSWORD: stockpass
    ports:
      - "8082:80"

volumes:
  db_data:
